name: MinigamesManager
version: 0.1.7
main: mc.jazhdo.Minigames
description: A plugin to manage minigames in JazhdoMC's minigames server
author: Jazhdo
website: https://github.com/jazhdomc/MinigamesManager

permissions:
  minigames.join:
    description: The ability to use the command /join and /leave
    default: true

commands:
  join:
    description: Joins a minigame
    usage: /join <game> <team_size>
    aliases: [enter]
    permission: minigames.join
  leave:
    description: Leaves a minigame
    usage: /leave
    permission: minigames.join